### ISSUE TITLE
Just why

### ISSUE THREAD

**Issue by IncognitoSquad** [Eman49exe/BlockRegenX#1]
the source is incredibly inefficient and why do you use like 60 else ifs, Why are you using priority, Why do you have different block break methods doing practically the same thing just checking different materials where you can just use the pipe symbol for or. fix up your code and become a better dev. that is the worst code i have seen in a WHILE.

Edit: also why is it in one class lmao

**Comment by IncognitoSquad** [comment]
i could honestly go on and on about the flaws in the code

**Comment by Eman49exe** [comment]
> the source is incredibly inefficient and why do you use like 60 else ifs, Why are you using priority, Why do you have different block break methods doing practically the same thing just checking different materials where you can just use the pipe symbol for or. fix up your code and become a better dev. that is the worst code i have seen in a WHILE.
> 
> Edit: also why is it in one class lmao

Hey man! Sorry it took a while to reply. I would like to say a few things

1: Made with a program called Visual Bukkit
2: Does not support class system
3: Plugin is no longer being worked on

**Comment by Eman49exe** [comment]
Also this is not a issue more of a complaint
